### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by benma** [kollivier/pyeverywhere#10]
Hi

Thanks for this. I am also interested in running a flask Python on Desktop standalone app as well as mobile apps using a web frontend. 

Do you still use this? Is Python 3 supported?

Thank you.

**Comment by kollivier** [comment]
Hi, 

Yes to both. I added Python 3 support a month or two ago. I'd love to have a flask template, actually, so new projects could do something like `pew create --template=flask myapp` to get a hello world Flask application to start from!

Thanks,

Kevin
